import { house1images } from './assets'

export const housesData = [
  {
    id: 1,
    name: 'Whitefish Estate',
    location: 'Whitefish, Montana, United States',
    price_per_night: 10000,
    images: house1images,
    beds: 8,
    rooms: 8,
    guests: 16,
    baths: 8,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 2,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 3,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 4,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 5,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 6,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 7,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 8,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 9,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 10,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 11,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 12,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
  {
    id: 13,
    name: '',
    location: '',
    price_per_night: '',
    images: [],
    beds: 5,
    rooms: 4,
    guests: 8,
    baths: 4,
    ratings: {
      cleanliness: 5,
      accuracy: 4.5,
      communication: 4.99,
      location: 4.8,
      check_in: 4.9,
      value: 4.2,
    },
  },
]
